dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_c94b40c9a248_key -iv $encrypted_c94b40c9a248_iv -in .env.enc -out .env -d

install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
- sudo apt update && apt-get install -y xsel
- sudo dpkg -i /tmp/hugo.deb
script:
- hugo
- bash deploy.sh
